-- Compare Local and Cloud Database Schemas
-- Run this on BOTH databases and compare results

-- Get column counts for each table
SELECT 
    t.TABLE_NAME,
    COUNT(c.COLUMN_NAME) AS ColumnCount,
    STRING_AGG(c.COLUMN_NAME, ', ') AS Columns
FROM INFORMATION_SCHEMA.TABLES t
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_NAME = c.TABLE_NAME
WHERE t.TABLE_TYPE = 'BASE TABLE'
GROUP BY t.TABLE_NAME
ORDER BY t.TABLE_NAME;

-- Check for missing columns in critical tables
SELECT 'Products' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Products'
ORDER BY ORDINAL_POSITION;

SELECT 'SalesOrders' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SalesOrders'
ORDER BY ORDINAL_POSITION;

SELECT 'Customers' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Customers'
ORDER BY ORDINAL_POSITION;
