<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Radzen.Blazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModernSys.Data\ModularSys.Data.csproj" />
    <ProjectReference Include="..\ModularSys.Core\ModularSys.Core.csproj" />
  </ItemGroup>

</Project>
